export enum userActions {
  CHANGE_LANG_TYPE = 'CHANGE_LANG_TYPE',
  UPDATE_USER_INFO = 'UPDATE_USER_INFO',
  UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE',
}

export enum authActions {
  SET_TOKEN = 'SET_TOKEN',
  REMOVE_TOKEN = 'REMOVE_TOKEN',
  CHANGE_USER_ROLE = 'CHANGE_USER_ROLE',
}

export enum stepperActions {
  TRIGGER_STEPPER_ACTION = 'TRIGGER_STEPPER_ACTION',
  REST_STEPPER_ACTION = 'REST_STEPPER_ACTION',
  SET_STEPPER_LIST_COUNT = 'SET_STEPPER_LIST_COUNT',
}

export enum signupActionsTypes {
  SET_USER_DATA = 'SET_USER_DATA',
  RESET_SIGNUP_DATA = 'RESET_SIGNUP_DATA',
}

export enum paymentActions {
  SET_PAYMNET_DATA = 'SET_PAYMNET_DATA',
}
